<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go to checkout</name>
   <tag></tag>
   <elementGuidId>58dee059-e02a-4787-81ec-d79414e6b3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn--primary.btn--large</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83a3c258-d4b6-410a-9e09-1ced6aed1b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76cf24d6-9a91-459d-bba2-94c52110a061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--large</value>
      <webElementGuid>0b4277e3-f186-4973-9bd5-f659d5508663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49d8ed5e-c1f9-4c5b-b3d0-d32ee63395f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>cta-bottom</value>
      <webElementGuid>3a32f198-de1a-49d8-a9e0-5b9f0a7f620c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>[{&quot;eventFamily&quot;:&quot;CART&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;flushImmediately&quot;:false,&quot;operationId&quot;:&quot;4451299&quot;,&quot;eventProperty&quot;:{&quot;sid&quot;:&quot;p4451299.m152688.l165170&quot;,&quot;actionKind&quot;:&quot;CLICK&quot;,&quot;imp&quot;:4451299,&quot;pge&quot;:4451299,&quot;ebc&quot;:&quot;9568372368&quot;}}]</value>
      <webElementGuid>9fdd5843-11c3-4f4a-aaa2-79a4e77bfaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;CART&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;flushImmediately&quot;:false,&quot;operationId&quot;:&quot;4451299&quot;,&quot;eventProperty&quot;:{&quot;sid&quot;:&quot;p4451299.m152688.l165170&quot;,&quot;actionKind&quot;:&quot;CLICK&quot;,&quot;imp&quot;:4451299,&quot;pge&quot;:4451299,&quot;ebc&quot;:&quot;9568372368&quot;}}</value>
      <webElementGuid>f844f1c8-f88f-4aec-ab69-e6620a364936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to checkout</value>
      <webElementGuid>ace735e1-859a-4434-909e-dee33d2a93a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;app-dsk&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;right-column&quot;]/div[@class=&quot;cartsummary sticky dweb-order-summary-optimization&quot;]/div[@class=&quot;cart-summary-call-to-action&quot;]/button[@class=&quot;btn btn--primary btn--large&quot;]</value>
      <webElementGuid>e33fde1a-c87b-458c-92fc-93a8f4972869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>a9ea5320-f2f5-4d52-aa57-5ea8be4ec698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>d11a5109-286c-467c-8779-832edefac8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US $109.80'])[1]/following::button[1]</value>
      <webElementGuid>15c61e44-35ea-447e-997e-9ce5b639e427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/following::button[1]</value>
      <webElementGuid>34853796-1ec9-4c94-b21b-e2d3a8344581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase protected by'])[1]/preceding::button[1]</value>
      <webElementGuid>5ade60cc-d95c-4a17-abaf-cc2dddbfd5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eBay Money Back Guarantee'])[1]/preceding::button[1]</value>
      <webElementGuid>6c15bd11-bd74-46ed-af9f-1b3ad989ef8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to checkout']/parent::*</value>
      <webElementGuid>71f45098-bdd9-453a-a536-30fd996fd749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3abd7ab5-8914-497b-b6ef-aab7d2636b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Go to checkout' or . = 'Go to checkout')]</value>
      <webElementGuid>7366f660-f32a-43cc-b5ec-545cd3ccb461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
