<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>4ea8e07d-f3d8-47bb-ad8a-b7db1d4e363a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sgnBt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sgnBt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ea5a2c0-eaa5-482c-8bf5-f0e9c73ce454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sgnBt</value>
      <webElementGuid>5fec943c-14e3-45f4-84e9-00fed56c7f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sgnBt</value>
      <webElementGuid>a617f87d-5ed0-42d3-86b4-49c3413f7479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-viewport</name>
      <type>Main</type>
      <value>{&quot;trackableId&quot;:&quot;01HQMGE7VX6CENN9TW6AAV15CA&quot;}</value>
      <webElementGuid>0a48e10e-5d1b-4463-9140-be949108efc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactions</name>
      <type>Main</type>
      <value>[{&quot;eventFamily&quot;:&quot;IDENTITY&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;CLICK&quot;,&quot;flushImmediately&quot;:false,&quot;operationId&quot;:2487285,&quot;eventProperty&quot;:{&quot;sid&quot;:&quot;p2487285.m5021.l160982&quot;}}]</value>
      <webElementGuid>eb7cecb9-1336-4233-9700-855f14993e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--fluid btn--large btn--primary</value>
      <webElementGuid>56cc5b92-25f5-4c1e-ae13-45d962d48f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21d14ea0-8188-4c66-b061-f8f95d6ab79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign in</value>
      <webElementGuid>5f338781-0e14-43df-b1fe-86a4d0fb79db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sgnBt&quot;)</value>
      <webElementGuid>869c03d1-59d6-47e6-bc37-2d83f47dff6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sgnBt']</value>
      <webElementGuid>5f516849-0ffc-4459-8bd5-f10b00f8ac0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin-form']/div/div[3]/div/button</value>
      <webElementGuid>b4b78f67-7231-42ff-a9fb-a672942194fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>c9fe15ff-33cc-45da-a95b-dc6aeeee7934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help signing in?'])[1]/preceding::button[1]</value>
      <webElementGuid>33006dce-2162-4408-81d6-49975bc4de33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>93d35f82-8b82-42ce-be0d-da9d28c95709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>4a4a3486-ea4a-4ca4-8f51-a5a627f7d557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sgnBt' and @name = 'sgnBt' and @type = 'button' and (text() = ' Sign in' or . = ' Sign in')]</value>
      <webElementGuid>226ea9be-14e6-40ff-a6b1-d7d8dd4082e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
