<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>7965176c-3da9-4b84-b40e-22f03d3fc84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin-continue-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signin-continue-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c200917b-e532-4712-92a6-e3730dbda73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-continue-btn</value>
      <webElementGuid>dc16246d-8628-4ac0-a84e-5bcead0a8b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signin-continue-btn</value>
      <webElementGuid>7b7cd948-491c-4733-b255-a8d4cf142553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-viewport</name>
      <type>Main</type>
      <value>{&quot;trackableId&quot;:&quot;01HQMGDV3JZ8XDMARBJJJFFTTG&quot;}</value>
      <webElementGuid>cff7f7fa-897f-4734-8d8e-f55df4fe09f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactions</name>
      <type>Main</type>
      <value>[{&quot;eventFamily&quot;:&quot;IDENTITY&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;CLICK&quot;,&quot;flushImmediately&quot;:false,&quot;eventProperty&quot;:{&quot;sid&quot;:&quot;p2487283.m5021.l46828&quot;},&quot;operationId&quot;:&quot;2487283&quot;}]</value>
      <webElementGuid>4a970c18-5a47-4fcd-a8c1-0d5caf217ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--fluid btn--large-truncated btn--primary</value>
      <webElementGuid>3cf1aad6-1fdb-47a9-8bc7-1617910d1ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a0327ac-4854-438b-804d-e7646f4b203e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>e9992039-c753-45a9-83ea-059112034ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-continue-btn&quot;)</value>
      <webElementGuid>bafc124b-f418-499b-bc69-070a17bee675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signin-continue-btn']</value>
      <webElementGuid>0251f748-5e04-4eda-a562-46f00aeb69cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin-form']/div/div/div/div/div/button</value>
      <webElementGuid>a0e2856a-2d6f-4f27-9bad-34132b08397b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email or username'])[1]/following::button[1]</value>
      <webElementGuid>9028ca3b-d9d6-44ff-bfff-947dc045ee40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create an account'])[1]/following::button[1]</value>
      <webElementGuid>449e80bc-4ade-4543-81f1-daea28e94384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/preceding::button[1]</value>
      <webElementGuid>9dd8fedd-0582-4b90-8648-6475ecf8ff58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::button[1]</value>
      <webElementGuid>d66d8146-d9f3-4897-a163-018bba589bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>d898e503-54bc-4e29-a375-7f0d35fe7e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>00dcd174-050f-4d9c-9240-2d01514f9924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'signin-continue-btn' and @name = 'signin-continue-btn' and @type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>159751d2-2681-4c0a-ba14-78405f08fcf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
