<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_show-password-checkbox</name>
   <tag></tag>
   <elementGuidId>d79ce8f9-26de-4246-8f5c-5d3301c582a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-password-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-password-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4cd4ba9-e3da-4fce-bdb5-edd2e0b2b26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-password-checkbox</value>
      <webElementGuid>ffe7e98c-4816-4d85-b2be-525950a1ff85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show password</value>
      <webElementGuid>7568bd72-9397-4c58-9038-5102da565bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>event.preventDefault();</value>
      <webElementGuid>6693ae04-d1e0-474b-91da-004367c32497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox__control</value>
      <webElementGuid>8916c22e-6869-479c-a8a9-13e24bce79db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6a1fbbf3-871d-4473-a9f6-1c3ed39a169a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-password-checkbox&quot;)</value>
      <webElementGuid>0d7ca578-21dd-4557-aa1d-187c3d5608cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-password-checkbox']</value>
      <webElementGuid>91b9b0d0-cc54-484a-a8fb-387528ba725a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-password-div']/span/input</value>
      <webElementGuid>7a06118d-3bff-4de6-bc3e-a76fcdfba9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>8e96d6da-e3f2-48ec-8b61-881c4e15aa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'show-password-checkbox' and @type = 'checkbox']</value>
      <webElementGuid>233e5fdf-ba9a-4bf8-a856-93ef01fe0f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
